### ISSUE TITLE
.DS_Store should not be in the project

### ISSUE THREAD

**Issue by lpatiny** [kjappelbaum/isotherm-analysis#7]
Strange because it is in .gitignore and it should not be there I think. Maybe you forced add ?

**Comment by kjappelbaum** [comment]
I think it is since you added it it later in the generator and i then realized that it is not there (this is the reason I made the PR https://github.com/cheminfo/generator-cheminfo/pull/27), added it to the `.gitignore` but did not clean the history yet.

**Comment by kjappelbaum** [comment]
Thanks for reporting, should be resolved.
